#!/bin/bash
#SBATCH --job-name=pre2
#SBATCH --output=logs/slurm/pre2_%A_%a.out
#SBATCH --error=logs/slurm/pre2_%A_%a.err
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=8G
#SBATCH --array=1-520
#SBATCH --requeue

# Does pretraining + active learning actually augment naive, once the three
# implementation defects found on 2026-08-10 are removed?
#
# The old M3 result ("pretraining never wins") was measured through three bugs:
#
#   1. OBJECTIVE MISMATCH. Pretraining used MSE onto the partial's raw per-state
#      values; RLHF then switches to Bradley-Terry, which reads the summed
#      fragment difference as a LOGIT. MSE pins the output magnitude to whatever
#      scale the partial happens to have, so the model starts out confidently
#      wrong. Measured in the archive: on LunarLander the MSE-pretrained model
#      ranks 66% of held-out pairs correctly yet scores BT loss 2.81 against a
#      chance level of 0.69 - an implied margin of ~8 nats where its accuracy
#      justifies ~0.7. Fix: --pretrain-loss bt, which trains on preference
#      labels generated by the partial itself. Those labels are free (the
#      partial is a known function) and are NOT charged to the query budget.
#      Verified locally, same seed and data: BT_before 2.416 (mse) -> 1.021 (bt).
#
#   2. DATA LEAK. trainer.py pretrained on the round-0 rollout and then drew the
#      round-0 queries from that same rollout, so the model was asked about the
#      exact states it had just memorised. That makes "a pretrained model picks
#      better queries" - the entire cold-start claim - untestable. Fix:
#      --pretrain-holdout. Round 0 already collects 2x collection_timesteps, so
#      the split costs nothing. The bt_leak arm A/Bs it.
#
#   3. BUDGETS TOO HIGH TO SEE IT. The pretraining effect roughly HALVES from
#      350 to 700 queries in 8 of 10 archived cells, and 350 was the lowest
#      budget ever run. The ladder here goes down to 175.
#
# Everything is opt-in; with no flags the code behaves exactly as before.
#
# Envs: LunarLander-v3 (the clean env; collapse present) and Pusher-v5 (no
# collapse anywhere - the negative control). Hopper/Walker are deliberately
# absent: they are covered by run_e0tuned.sh and Hopper's true arm collapses on
# its own, so it cannot support any claim about reward-model overoptimization.
#
# --no-include-partial-feature is REQUIRED on every naive arm: if the partial is
# a model input, pretraining a network to predict an input it can already see is
# trivial and measures nothing.
#
# 10 seeds. The pre-vs-none contrast pools to n=20 pairs per (env, budget) over
# the AL factor. That is enough for an effect the size of the MSE damage
# (-57 at 350, p<0.001 in the archive) and marginal for anything subtler.

set -euo pipefail

module load mamba
source activate /scratch/work/akishea1/envs/rcomp
cd /scratch/work/akishea1/reward_composition_api/api

LINE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" jobs/params_pre2.txt)
read -r CELL VARIANT BUDGET SEED <<< "$LINE"

case "$CELL" in
  ll)
    SUITE=box2d;  ENV=LunarLander-v3; PARTIAL=lunar_lander_approach
    STEPS=2000000; EXTRA="--collection-timesteps 30000" ;;
  pusher)
    SUITE=mujoco; ENV=Pusher-v5;      PARTIAL=pusher_honest
    STEPS=3000000; EXTRA="" ;;
  *) echo "unknown cell: $CELL" >&2; exit 1 ;;
esac

# Defaults every arm shares, overridden per variant below.
MODE="naive"
PARTIAL_ARGS="--partial-alpha 1.0 --no-include-partial-feature"
PRE=""
AL="--active-learning"
ENSEMBLE=""
TANH=""

# --pretrain-holdout is ON for every pretraining arm except bt_leak, which is
# the deliberate control for the leak.
HOLDOUT="--pretrain-holdout"
BT="--pretrain-reward-model --pretrain-target partial --pretrain-loss bt"
MSE="--pretrain-reward-model --pretrain-target partial --pretrain-loss mse"

case "$VARIANT" in
  # --- main grid: pretraining objective x active learning -------------------
  none_al)      PRE="";                  AL="--active-learning" ;;
  none_noal)    PRE="";                  AL="--no-active-learning" ;;
  mse_al)       PRE="$MSE $HOLDOUT";     AL="--active-learning" ;;
  mse_noal)     PRE="$MSE $HOLDOUT";     AL="--no-active-learning" ;;
  bt_al)        PRE="$BT $HOLDOUT";      AL="--active-learning" ;;
  bt_noal)      PRE="$BT $HOLDOUT";      AL="--no-active-learning" ;;

  # --- E4: PEBBLE's actual AL = ensemble of 3 + disagreement ----------------
  # At ensemble size 1 the "auto" strategy silently becomes MC-dropout, which is
  # NOT what PEBBLE does, so the archived AL null never tested their method.
  none_ens3)    PRE="";              ENSEMBLE="--reward-model-ensemble-size 3 --active-query-strategy ensemble" ;;
  bt_ens3)      PRE="$BT $HOLDOUT";  ENSEMBLE="--reward-model-ensemble-size 3 --active-query-strategy ensemble" ;;

  # --- E5: the leak, i.e. bt_al without the holdout -------------------------
  bt_leak)      PRE="$BT" ;;

  # --- E6: cheating ceiling for pretraining-as-initialisation ---------------
  # Labels from the TRUE reward. Not a method - an upper bound. If this does not
  # beat plain naive either, then an initialisation cannot substitute for a
  # persistent prior no matter how good the pretraining signal is, and M3 is
  # dead for a reason stronger than "our partial was bad".
  true_al)      PRE="--pretrain-reward-model --pretrain-target true --pretrain-loss bt $HOLDOUT" ;;

  # --- E7: PEBBLE's tanh-bounded reward model -------------------------------
  # model_reward_min/max only clip in the wrapper AFTER training; tanh bounds
  # inside the model, where it shapes the Bradley-Terry loss landscape.
  tanh_naive)    TANH="--tanh-model-reward" ;;
  tanh_feedback) TANH="--tanh-model-reward"; MODE="feedback"; PARTIAL_ARGS="" ;;

  # --- vanilla RLHF reference at the new bottom rung ------------------------
  fb_al)        MODE="feedback"; PARTIAL_ARGS="" ;;

  *) echo "unknown variant: $VARIANT" >&2; exit 1 ;;
esac

LOGDIR="logs/pre2_${CELL}_${VARIANT}"
RUNNAME="${CELL}_${VARIANT}_q${BUDGET}_seed${SEED}"

if [ -f "${LOGDIR}/${RUNNAME}/metadata.json" ]; then
  echo "already complete: ${LOGDIR}/${RUNNAME}"
  exit 0
fi

# --final-policy last: the default 'best' is a best-of-N checkpoint pick scored
# on the ground-truth reward, which no real RLHF pipeline can do and which hides
# exactly the collapse this project is about.
# --reward-model-diagnostics: records held-out BT loss and accuracy BEFORE any
# preference training, which is how the objective fix gets measured directly
# rather than inferred from policy scores.
# --query-fisher-diagnostic: records how informative the queries the selector
# chose actually were, which is the cold-start claim.
srun python -m rcomp train \
  --suite "$SUITE" --env-id "$ENV" --partial "$PARTIAL" \
  --mode "$MODE" $PARTIAL_ARGS \
  $PRE $AL $ENSEMBLE $TANH $EXTRA \
  --final-policy last \
  --reward-model-diagnostics --query-fisher-diagnostic \
  --query-budget "$BUDGET" --rlhf-rounds 5 \
  --timesteps "$STEPS" --seed "$SEED" \
  --eval-freq 50000 --n-eval-episodes 20 \
  --run-name "$RUNNAME" --log-dir "$LOGDIR"
