"""Preference-based reward learning: trajectory fragmenting, synthetic
rating, query-pair selection (random / MC-dropout / ensemble variance), and
reward-model (pre)training with pairwise Bradley-Terry or delta losses."""

from __future__ import annotations

import math
import random
from copy import deepcopy
from typing import Callable

import numpy as np
import torch as th
from torch.optim import Adam

from ..data import Preference, Trajectory
from .model import (
    DeltaLoss,
    OutputRegularizationLoss,
    PairwiseLoss,
    RegularizationLoss,
    RewardModel,
    preference_prob,
)


def rate_pairs_from_true_reward(pairs: list[tuple[Trajectory, Trajectory]]) -> list[Preference]:
    rated_pairs = []
    for t1, t2 in pairs:
        rated_pairs.append(Preference(t1, t2, float(t1.get_summed_reward() > t2.get_summed_reward())))
    return rated_pairs


def _fragment_score(trajectory: Trajectory, target: str) -> float:
    """Summed return of a fragment under one of the pretraining targets."""
    if target == "partial":
        return trajectory.get_summed_partial_reward()
    if target == "true":
        return trajectory.get_summed_reward()
    if target == "residual":
        return trajectory.get_summed_reward() - trajectory.get_summed_partial_reward()
    raise ValueError(f"Unsupported pretrain target: {target}")


def _target_preference_rating(
    score1: float,
    score2: float,
    *,
    temperature: float | None = None,
    tie_margin: float | None = None,
) -> float:
    """Convert a target-return difference into a hard or soft preference.

    With both optional arguments omitted this deliberately preserves the
    historical label exactly, including assigning an exact tie to the second
    fragment.  A non-negative ``tie_margin`` opts into explicit 0.5 labels for
    near ties.  A positive ``temperature`` opts into a logistic teacher whose
    confidence changes smoothly with the target-return gap.
    """
    if temperature is not None and temperature <= 0:
        raise ValueError("temperature must be greater than zero")
    if tie_margin is not None and tie_margin < 0:
        raise ValueError("tie_margin must be non-negative")

    difference = float(score1 - score2)
    if tie_margin is not None and abs(difference) <= tie_margin:
        return 0.5
    if temperature is None:
        return float(difference > 0)

    scaled = difference / temperature
    # Stable sigmoid: avoid exp(+large) without adding a scipy dependency.
    if scaled >= 0:
        exp_negative = math.exp(-scaled)
        return 1.0 / (1.0 + exp_negative)
    exp_positive = math.exp(scaled)
    return exp_positive / (1.0 + exp_positive)


def rate_pairs_from_target(
    pairs: list[tuple[Trajectory, Trajectory]],
    target: str,
    *,
    temperature: float | None = None,
    tie_margin: float | None = None,
) -> list[Preference]:
    """Synthetic preference labels generated by the hand-written partial (or another
    target) instead of by a human. These cost nothing: the partial is a known
    function, so the label budget for pretraining is unlimited and is NOT charged
    against the query budget."""
    rated_pairs = []
    for t1, t2 in pairs:
        rating = _target_preference_rating(
            _fragment_score(t1, target),
            _fragment_score(t2, target),
            temperature=temperature,
            tie_margin=tie_margin,
        )
        rated_pairs.append(Preference(t1, t2, rating))
    return rated_pairs


def fragment_trajectories(trajectories: list[Trajectory], fragment_length: int) -> list[Trajectory]:
    fragments = []
    for trajectory in trajectories:
        states = trajectory.get_states()
        for start_idx in range(0, len(states), fragment_length):
            if start_idx + fragment_length <= len(states):
                fragments.append(Trajectory(states[start_idx : start_idx + fragment_length]))
    return fragments


def random_query_pairs(
    fragments: list[Trajectory],
    query_count: int,
    rng: random.Random | None = None,
) -> list[tuple[Trajectory, Trajectory]]:
    shuffled = list(fragments)
    (rng.shuffle if rng is not None else random.shuffle)(shuffled)
    return list(zip(shuffled[::2], shuffled[1::2]))[:query_count]


def dropout_active_learning_pairs(
    fragments: list[Trajectory],
    reward_model: RewardModel,
    query_count: int,
    convert_traj: Callable[[Trajectory], list[list[float]]],
    add_partial_to_predictions: bool,
    k: int,
    dropout_p: float,
    n_batches: int,
    transform_partial: Callable[[float], float] | None = None,
    rng: random.Random | None = None,
    candidate_protocol: str = "matching",
    pool_multiplier: int = 10,
) -> list[tuple[Trajectory, Trajectory]]:
    if len(fragments) < 2:
        return []

    mc_dropout_models = [deepcopy(reward_model).dropout(dropout_p) for _ in range(k)]
    fragment_tensor = th.as_tensor([convert_traj(fragment) for fragment in fragments], dtype=th.float32)
    partial_returns = _partial_fragment_returns(fragments, transform_partial)

    pred_returns = []
    with th.no_grad():
        for model in mc_dropout_models:
            returns = th.sum(model(fragment_tensor), dim=[1, 2]).detach().cpu().numpy().tolist()
            if add_partial_to_predictions:
                returns = [model_return + partial for model_return, partial in zip(returns, partial_returns)]
            pred_returns.append(returns)

    return _select_pairs(fragments, pred_returns, query_count, n_batches, rng, candidate_protocol, pool_multiplier)


def _select_pairs(fragments, pred_returns, query_count, n_batches, rng, candidate_protocol, pool_multiplier):
    if candidate_protocol == "pool":
        return _candidate_pool_pairs(fragments, pred_returns, query_count, pool_multiplier, rng=rng)
    return _preference_variance_pairs(fragments, pred_returns, query_count, n_batches, rng=rng)


def ensemble_active_learning_pairs(
    fragments: list[Trajectory],
    reward_models: list[RewardModel],
    query_count: int,
    convert_traj: Callable[[Trajectory], list[list[float]]],
    add_partial_to_predictions: bool,
    n_batches: int,
    transform_partial: Callable[[float], float] | None = None,
    rng: random.Random | None = None,
    candidate_protocol: str = "matching",
    pool_multiplier: int = 10,
) -> list[tuple[Trajectory, Trajectory]]:
    if len(fragments) < 2 or not reward_models:
        return []

    fragment_tensor = th.as_tensor([convert_traj(fragment) for fragment in fragments], dtype=th.float32)
    partial_returns = _partial_fragment_returns(fragments, transform_partial)

    pred_returns = []
    with th.no_grad():
        for model in reward_models:
            returns = th.sum(model(fragment_tensor), dim=[1, 2]).detach().cpu().numpy().tolist()
            if add_partial_to_predictions:
                returns = [model_return + partial for model_return, partial in zip(returns, partial_returns)]
            pred_returns.append(returns)

    return _select_pairs(fragments, pred_returns, query_count, n_batches, rng, candidate_protocol, pool_multiplier)


def _partial_fragment_returns(fragments: list[Trajectory], transform_partial: Callable[[float], float] | None) -> list[float]:
    transform = transform_partial or (lambda value: value)
    return [sum(transform(state["partial_rew"]) for state in fragment.states) for fragment in fragments]


def _pair_disagreement(pred_returns: list[list[float]], pairs: list[tuple[int, int]]) -> np.ndarray:
    """Ensemble variance of the predicted preference probability, per candidate pair."""
    scores = th.as_tensor(
        [[(pred_returns[m][i], pred_returns[m][j]) for i, j in pairs] for m in range(len(pred_returns))],
        dtype=th.float32,
    )
    return th.sum(th.var(preference_prob(scores, 2), dim=0), dim=1).detach().cpu().numpy()


def _candidate_pool_pairs(
    fragments: list[Trajectory],
    pred_returns: list[list[float]],
    query_count: int,
    pool_multiplier: int,
    rng: random.Random | None = None,
) -> list[tuple[Trajectory, Trajectory]]:
    """B-Pref's disagreement sampling: draw an INDEPENDENT candidate pool of
    ``pool_multiplier * query_count`` pairs, score each one, and keep the top-k.

    The alternative in ``_preference_variance_pairs`` scores whole perfect
    matchings and keeps the best one, which is a different estimator: a fragment
    can appear in at most one pair per matching, so the selected set is
    constrained by a global matching rather than by per-pair informativeness, and
    the "best of N matchings" step optimizes the SUM over a matching instead of
    picking the individually most informative queries. B-Pref (Appendix C) states
    it generates an initial batch of N_inter pairs uniformly at random and then
    selects the N_query pairs with high uncertainty, which is what this does.
    """
    n = len(fragments)
    if n < 2 or query_count <= 0:
        return []
    picker = rng if rng is not None else random
    wanted = max(query_count * max(pool_multiplier, 1), query_count)

    seen: set[tuple[int, int]] = set()
    pool: list[tuple[int, int]] = []
    # cap the attempts so a tiny fragment set cannot spin: with n fragments there
    # are only n*(n-1)/2 distinct unordered pairs to find.
    for _ in range(wanted * 10):
        if len(pool) >= wanted:
            break
        i, j = picker.randrange(n), picker.randrange(n)
        if i == j:
            continue
        key = (i, j) if i < j else (j, i)
        if key in seen:
            continue
        seen.add(key)
        pool.append((i, j))
    if not pool:
        return random_query_pairs(fragments, query_count, rng=rng)

    variances = _pair_disagreement(pred_returns, pool)
    ranked = sorted(zip(pool, variances), key=lambda item: item[1], reverse=True)
    return [(fragments[i], fragments[j]) for (i, j), _ in ranked[:query_count]]


def _preference_variance_pairs(
    fragments: list[Trajectory],
    pred_returns: list[list[float]],
    query_count: int,
    n_batches: int,
    rng: random.Random | None = None,
) -> list[tuple[Trajectory, Trajectory]]:
    possible_indices = list(range(len(fragments)))
    best_indices_batch = None
    best_vars = None
    best_score = -float("inf")

    for _ in range(n_batches):
        (rng.shuffle if rng is not None else random.shuffle)(possible_indices)
        indices_batch = list(zip(possible_indices[::2], possible_indices[1::2]))
        if not indices_batch:
            continue
        pair_returns = th.as_tensor(
            [
                [(pred_returns[model_idx][i], pred_returns[model_idx][j]) for i, j in indices_batch]
                for model_idx in range(len(pred_returns))
            ],
            dtype=th.float32,
        )
        pred_preferences = preference_prob(pair_returns, 2)
        variances = th.sum(th.var(pred_preferences, dim=0), dim=1).detach().cpu().numpy()
        score = float(np.sum(variances))
        if score > best_score:
            best_score = score
            best_indices_batch = indices_batch
            best_vars = variances

    if best_indices_batch is None or best_vars is None:
        return random_query_pairs(fragments, query_count, rng=rng)

    ranked = sorted(zip(best_indices_batch, best_vars), key=lambda item: item[1], reverse=True)
    return [(fragments[i], fragments[j]) for (i, j), _ in ranked[:query_count]]


def choose_query_pairs(
    trajectories: list[Trajectory],
    reward_model: RewardModel | list[RewardModel] | None,
    query_count: int,
    fragment_length: int,
    active_learning: bool,
    convert_traj: Callable[[Trajectory], list[list[float]]],
    add_partial_to_predictions: bool,
    dropout_samples: int,
    dropout_p: float,
    active_learning_batches: int,
    active_query_strategy: str = "auto",
    transform_partial: Callable[[float], float] | None = None,
    rng: random.Random | None = None,
    candidate_protocol: str = "matching",
    pool_multiplier: int = 10,
) -> list[tuple[Trajectory, Trajectory]]:
    fragments = fragment_trajectories(trajectories, fragment_length)
    if len(fragments) < 2 or query_count <= 0:
        return []
    if reward_model is None or not active_learning:
        return random_query_pairs(fragments, query_count, rng=rng)

    reward_models = reward_model if isinstance(reward_model, list) else [reward_model]
    if active_query_strategy == "auto":
        active_query_strategy = "ensemble" if len(reward_models) > 1 else "dropout"
    if active_query_strategy == "ensemble" and len(reward_models) > 1:
        return ensemble_active_learning_pairs(
            fragments,
            reward_models,
            query_count,
            convert_traj,
            add_partial_to_predictions,
            active_learning_batches,
            transform_partial,
            rng,
            candidate_protocol,
            pool_multiplier,
        )

    return dropout_active_learning_pairs(
        fragments,
        reward_models[0],
        query_count,
        convert_traj,
        add_partial_to_predictions,
        dropout_samples,
        dropout_p,
        active_learning_batches,
        transform_partial,
        rng,
        candidate_protocol,
        pool_multiplier,
    )


def split_holdout_trajectories(
    trajectories: list[Trajectory],
    pair_count: int,
    fragment_length: int,
    rng: random.Random,
) -> tuple[list[Trajectory], list[Trajectory]]:
    """Reserve whole trajectories for a diagnostic set no query is ever drawn from.

    Splitting at the TRAJECTORY level rather than the fragment level matters: two
    fragments cut from the same episode share its initial state and policy, so a
    fragment-level split would leave the diagnostic set correlated with training.
    Returns ``(query_trajectories, holdout_trajectories)``; the holdout is empty
    when ``pair_count`` is zero or nothing can be spared.
    """
    if pair_count <= 0 or not trajectories:
        return list(trajectories), []
    shuffled = list(trajectories)
    rng.shuffle(shuffled)
    needed = 2 * pair_count
    holdout, reserved_fragments = [], 0
    for index, trajectory in enumerate(shuffled):
        if reserved_fragments >= needed:
            break
        available = len(trajectory.get_states()) // fragment_length
        if available <= 0:
            continue
        # Never take the last usable trajectory; the query pool must survive.
        if len(shuffled) - index <= 1:
            break
        holdout.append(trajectory)
        reserved_fragments += available
    held = {id(trajectory) for trajectory in holdout}
    remaining = [trajectory for trajectory in shuffled if id(trajectory) not in held]
    if not remaining:
        return list(trajectories), []
    return remaining, holdout


def build_holdout_preferences(
    holdout_trajectories: list[Trajectory],
    pair_count: int,
    fragment_length: int,
    rng: random.Random,
) -> list[Preference]:
    """Uniformly sampled pairs from the reserved trajectories, rated by the TRUE
    reward. These are the experimenter's oracle yardstick: they measure how often
    the reward model's ranking agrees with the ground-truth ranking on data no
    member was fit on. They are deliberately uniform, never actively selected, so
    the diagnostic does not move when the query strategy changes."""
    fragments = fragment_trajectories(holdout_trajectories, fragment_length)
    if len(fragments) < 2:
        return []
    return rate_pairs_from_true_reward(random_query_pairs(fragments, pair_count, rng=rng))


def rated_pairs_to_tensors(rated_pairs: list[Preference], convert_traj: Callable[[Trajectory], list[list[float]]]):
    t1s, t2s, ratings = [], [], []
    for pair in rated_pairs:
        t1s.append(convert_traj(pair.t1))
        t2s.append(convert_traj(pair.t2))
        ratings.append(pair.rating)
    return (
        th.as_tensor(t1s, dtype=th.float32),
        th.as_tensor(t2s, dtype=th.float32),
        th.as_tensor(ratings, dtype=th.float32),
    )


def partial_reward_tensor(rated_pairs: list[Preference], side: str, partial_mean: float = 0.0, partial_std: float = 1.0):
    trajectories = [pair.t1 if side == "t1" else pair.t2 for pair in rated_pairs]
    rewards = [
        [[(state["partial_rew"] - partial_mean) / max(partial_std, 1e-8)] for state in trajectory.states]
        for trajectory in trajectories
    ]
    return th.as_tensor(rewards, dtype=th.float32)


def reward_model_io_stats(
    reward_model: RewardModel | list[RewardModel],
    trajectories: list[Trajectory],
    convert_traj: Callable[[Trajectory], list[list[float]]],
):
    if not trajectories:
        return None, None
    reward_models = reward_model if isinstance(reward_model, list) else [reward_model]
    with th.no_grad():
        trajectory_tensors = th.as_tensor([convert_traj(trajectory) for trajectory in trajectories], dtype=th.float32)
        outputs = th.stack([model(trajectory_tensors).reshape(-1) for model in reward_models]).mean(dim=0)
    return float(outputs.mean().item()), float(outputs.std(unbiased=False).item())


def gate_statistics(reward_model, trajectories, convert_traj):
    """Distribution of the learned per-state gate g(s,a) over the given states."""
    reward_models = reward_model if isinstance(reward_model, list) else [reward_model]
    if not trajectories or reward_models[0].gate_head is None:
        return None
    with th.no_grad():
        tensors = th.as_tensor([convert_traj(trajectory) for trajectory in trajectories], dtype=th.float32)
        gates = th.stack([model.gate(tensors).reshape(-1) for model in reward_models]).mean(dim=0).cpu().numpy()
    return {
        "mean": float(gates.mean()),
        "std": float(gates.std()),
        "p10": float(np.percentile(gates, 10)),
        "p50": float(np.percentile(gates, 50)),
        "p90": float(np.percentile(gates, 90)),
        "frac_below_0.1": float((gates < 0.1).mean()),
        "frac_above_0.9": float((gates > 0.9).mean()),
    }


def reward_model_diagnostics(
    reward_model,
    pairs: list[Preference],
    convert_traj: Callable[[Trajectory], list[list[float]]],
    partial_mean: float = 0.0,
    partial_std: float = 1.0,
    partial_alpha: float = 1.0,
):
    """Bradley-Terry loss and ranking accuracy on held-out preference pairs.

    Three numbers, each answering a different question:

    - `bt_loss` / `accuracy`: how well the reward model ALONE explains
      preferences it was not trained on. Comparing this between a
      partial-pretrained model and a randomly initialised one is the direct
      test of whether pretraining gives the model a head start (M3).

    - `*_partial_ablated`: the same with the partial-reward input feature zeroed
      out. How much worse the model gets is how much it actually relies on that
      feature (M2). Note this is measured, not inferred from weights: the
      partial sits on a different numeric scale from the observations, so a
      small weight on it does not imply small influence, and comparing raw
      weight magnitudes across inputs mostly measures input scale.

    - `*_composed`: model + alpha*partial, i.e. the reward the policy actually
      trains on, so you can see whether the composition explains preferences
      better than the learned model on its own.
    """
    models = reward_model if isinstance(reward_model, list) else [reward_model]
    if not pairs or not models:
        return None

    loss_fn = PairwiseLoss()
    with th.no_grad():
        x1, x2, ratings = rated_pairs_to_tensors(pairs, convert_traj)
        p1 = partial_reward_tensor(pairs, "t1", partial_mean, partial_std) * partial_alpha
        p2 = partial_reward_tensor(pairs, "t2", partial_mean, partial_std) * partial_alpha

        def score(a, b):
            y1 = th.stack([m(a) for m in models]).mean(dim=0)
            y2 = th.stack([m(b) for m in models]).mean(dim=0)
            return y1, y2

        def summarize(y1, y2):
            loss = float(loss_fn(y1, y2, ratings).mean().item())
            pref = (y1.sum(dim=[1, 2]) > y2.sum(dim=[1, 2])).float()
            acc = float((pref == ratings).float().mean().item())
            return loss, acc

        y1, y2 = score(x1, x2)
        loss_plain, acc_plain = summarize(y1, y2)
        loss_comp, acc_comp = summarize(y1 + p1, y2 + p2)

        # ablate the partial feature: it is the LAST column of the model input
        # (reward_model_features concatenates obs, action, then the partial).
        a1, a2 = x1.clone(), x2.clone()
        a1[..., -1] = 0.0
        a2[..., -1] = 0.0
        ya1, ya2 = score(a1, a2)
        loss_abl, acc_abl = summarize(ya1, ya2)

    return {
        "n_pairs": len(pairs),
        "bt_loss": loss_plain,
        "accuracy": acc_plain,
        "bt_loss_partial_ablated": loss_abl,
        "accuracy_partial_ablated": acc_abl,
        "bt_loss_increase_when_ablated": loss_abl - loss_plain,
        "accuracy_drop_when_ablated": acc_plain - acc_abl,
        "bt_loss_composed": loss_comp,
        "accuracy_composed": acc_comp,
    }


def query_fisher_information(
    reward_model,
    pairs: list[Preference],
    convert_traj: Callable[[Trajectory], list[list[float]]],
    partial_mean: float = 0.0,
    partial_std: float = 1.0,
    partial_alpha: float = 1.0,
    add_partial: bool = False,
    max_pairs: int = 256,
):
    """How informative a set of preference queries is about the reward parameters.

    Under Bradley-Terry, asking about fragments A and B with
        p = sigmoid(R_A - R_B)
    contributes Fisher information
        I = p(1-p) * (dR_A - dR_B)(dR_A - dR_B)^T
    about the reward parameters. We report its trace,
        p(1-p) * ||dR_A - dR_B||^2,
    the standard scalar summary: how much the answer is expected to pin the
    parameters down. Two things make a query informative - the outcome must be
    uncertain (p near 0.5, so p(1-p) is large) AND the two fragments must be
    distinguishable by the parameters (large gradient difference). A query the
    model is already sure about carries almost no information however different
    the fragments are.

    This is the measurement for the cold-start claim: a reward model pretrained
    on the partial should pick queries with higher Fisher information at round 0
    than a randomly initialised one, which has no basis for choosing at all.

    The partial contributes a constant offset to the reward, so it shifts p but
    has no gradient of its own; with add_partial=True it is included in p only.
    """
    models = reward_model if isinstance(reward_model, list) else [reward_model]
    if not pairs or not models:
        return None
    sample = pairs if len(pairs) <= max_pairs else random.sample(list(pairs), max_pairs)

    scores = []
    for pair in sample:
        x1 = th.as_tensor([convert_traj(pair.t1)], dtype=th.float32)
        x2 = th.as_tensor([convert_traj(pair.t2)], dtype=th.float32)
        offset = 0.0
        if add_partial:
            p1 = float(sum((s["partial_rew"] - partial_mean) / max(partial_std, 1e-8) for s in pair.t1.states))
            p2 = float(sum((s["partial_rew"] - partial_mean) / max(partial_std, 1e-8) for s in pair.t2.states))
            offset = partial_alpha * (p1 - p2)

        per_model = []
        for model in models:
            model.zero_grad(set_to_none=True)
            diff = model(x1).sum() - model(x2).sum()
            grads = th.autograd.grad(diff, [p for p in model.parameters() if p.requires_grad], allow_unused=True)
            grad_sq = float(sum(float((g**2).sum()) for g in grads if g is not None))
            prob = float(th.sigmoid(diff.detach() + offset))
            per_model.append(prob * (1.0 - prob) * grad_sq)
        scores.append(float(np.mean(per_model)))

    scores = np.asarray(scores, dtype=np.float64)
    return {
        "n_pairs_scored": int(len(scores)),
        "fisher_mean": float(scores.mean()),
        "fisher_median": float(np.median(scores)),
        "fisher_total": float(scores.sum()),
    }


def _rankdata(x: np.ndarray) -> np.ndarray:
    """Ranks with ties averaged. Ties matter here: a gate that has collapsed to a
    constant is all ties, and naive argsort ranking would invent an ordering and
    report a spurious correlation for exactly the case we are trying to detect."""
    order = np.argsort(x, kind="mergesort")
    ranks = np.empty(len(x), dtype=np.float64)
    ranks[order] = np.arange(len(x), dtype=np.float64)
    sorted_x = x[order]
    start = 0
    while start < len(x):
        stop = start
        while stop + 1 < len(x) and sorted_x[stop + 1] == sorted_x[start]:
            stop += 1
        if stop > start:
            ranks[order[start : stop + 1]] = (start + stop) / 2.0
        start = stop + 1
    return ranks


def _spearman(a: np.ndarray, b: np.ndarray) -> float:
    """Rank correlation without a scipy dependency. Returns NaN when either side
    is constant (no variance => the correlation is undefined, not zero)."""
    if len(a) < 3:
        return float("nan")
    ra = _rankdata(np.asarray(a, dtype=np.float64))
    rb = _rankdata(np.asarray(b, dtype=np.float64))
    ra -= ra.mean()
    rb -= rb.mean()
    denom = float(np.sqrt((ra**2).sum() * (rb**2).sum()))
    return float((ra * rb).sum() / denom) if denom > 0 else float("nan")


def gate_partial_error_stats(reward_model, trajectories, convert_traj):
    """Does the gate actually distrust the partial where the partial is wrong?

    For every state we have the learned gate g(s,a), the hand-written partial,
    and the true reward. Partial and true reward live on different scales, so we
    standardize both and call |z(partial) - z(true)| the partial's error.

    Returns the rank correlation between g and that error. A per-state gate that
    is doing what it is meant to do gives a NEGATIVE correlation: the gate closes
    where the partial disagrees with the truth. A correlation near zero means the
    gate is not tracking the partial's reliability at all, whatever its effect on
    the final score - in that case a fixed alpha is the simpler equivalent.

    corr_gate_partial / corr_gate_true are controls: they show whether the gate is
    instead just following the magnitude of one of the two signals.
    """
    reward_models = reward_model if isinstance(reward_model, list) else [reward_model]
    if not trajectories or reward_models[0].gate_head is None:
        return None
    partial = np.array([state["partial_rew"] for t in trajectories for state in t.states], dtype=np.float64)
    true = np.array([state["rew"] for t in trajectories for state in t.states], dtype=np.float64)
    if len(partial) < 3:
        return None
    with th.no_grad():
        tensors = th.as_tensor([convert_traj(t) for t in trajectories], dtype=th.float32)
        gates = th.stack([m.gate(tensors).reshape(-1) for m in reward_models]).mean(dim=0).cpu().numpy()
    if len(gates) != len(partial):
        return None

    z_partial = (partial - partial.mean()) / max(float(partial.std()), 1e-8)
    z_true = (true - true.mean()) / max(float(true.std()), 1e-8)
    error = np.abs(z_partial - z_true)

    def _clean(value: float):
        # json.dump would happily write NaN/Infinity, which is not valid JSON
        return None if value is None or not np.isfinite(value) else float(value)

    high = gates[error >= np.median(error)]
    low = gates[error < np.median(error)]
    return {
        "n_states": int(len(gates)),
        "corr_gate_partial_error": _clean(_spearman(gates, error)),
        "corr_gate_partial": _clean(_spearman(gates, partial)),
        "corr_gate_true": _clean(_spearman(gates, true)),
        "mean_gate_high_error": _clean(high.mean()) if len(high) else None,
        "mean_gate_low_error": _clean(low.mean()) if len(low) else None,
    }


def pretrain_reward_model(
    reward_model: RewardModel,
    trajectories: list[Trajectory],
    convert_traj: Callable[[Trajectory], list[list[float]]],
    target: str,
    epochs: int,
    batch_size: int,
    learning_rate: float,
) -> None:
    rows = []
    targets = []
    for trajectory in trajectories:
        converted = convert_traj(trajectory)
        for converted_state, raw_state in zip(converted, trajectory.states):
            rows.append(converted_state)
            if target == "partial":
                targets.append([float(raw_state["partial_rew"])])
            elif target == "residual":
                targets.append([float(raw_state["rew"] - raw_state["partial_rew"])])
            elif target == "true":
                targets.append([float(raw_state["rew"])])
            else:
                raise ValueError(f"Unsupported pretrain target: {target}")

    if not rows:
        return

    x = th.as_tensor(rows, dtype=th.float32)
    y = th.as_tensor(targets, dtype=th.float32)
    optimizer = Adam(reward_model.parameters(), lr=learning_rate)
    loss_fn = th.nn.MSELoss()

    for epoch in range(epochs):
        order = th.randperm(x.shape[0])
        running_loss = 0.0
        batches = 0
        for batch_start in range(0, x.shape[0], batch_size):
            batch_indices = order[batch_start : batch_start + batch_size]
            pred = reward_model(x[batch_indices])
            loss = loss_fn(pred, y[batch_indices])
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            running_loss += float(loss.item())
            batches += 1
        print(f"pretrain epoch {epoch}: mse={running_loss / max(batches, 1):.6f}")


def pretrain_reward_model_bt(
    reward_model: RewardModel,
    trajectories: list[Trajectory],
    convert_traj: Callable[[Trajectory], list[list[float]]],
    target: str,
    epochs: int,
    batch_size: int,
    learning_rate: float,
    fragment_length: int,
    max_pairs: int = 0,
    patience: int = 10,
    temperature: float | None = None,
    tie_margin: float | None = None,
    loss_reduction: str = "sum",
    weight_l1: float = 0.0,
    output_l1: float = 0.0,
) -> dict | None:
    """Pretrain on the partial with the SAME objective preference learning uses.

    The MSE variant (`pretrain_reward_model`) regresses the network onto the
    partial's raw per-state values, which pins the output MAGNITUDE to whatever
    scale the partial happens to have. Bradley-Terry does not care about the
    ranking alone - it reads the summed fragment difference as a logit, so an
    over-large scale means the model is confidently wrong wherever the partial
    disagrees with the eventual preferences. That is measurable in the archived
    runs: on LunarLander the MSE-pretrained model ranks 66% of held-out pairs
    correctly yet scores a BT loss of 2.81 against a chance level of 0.69, i.e.
    an implied margin of ~8 nats where its accuracy justifies ~0.7.

    Training on partial-generated preference labels aligns the pretraining data
    term with downstream preference fitting. Hard pseudo-labels can themselves
    become overconfident, so ``temperature`` optionally supplies logistic soft
    labels and ``tie_margin`` optionally maps near-ties to 0.5. The labels are
    free - the partial is a known function - so this does not consume the human
    query budget.
    """
    fragments = fragment_trajectories(trajectories, fragment_length)
    if loss_reduction not in ("sum", "mean"):
        raise ValueError("loss_reduction must be 'sum' or 'mean'")
    if weight_l1 < 0 or output_l1 < 0:
        raise ValueError("BT-pretraining L1 penalties must be non-negative")
    if len(fragments) < 4:
        print(f"skipping BT pretraining: only {len(fragments)} fragments available")
        return None

    shuffled = list(fragments)
    random.shuffle(shuffled)
    pairs = list(zip(shuffled[::2], shuffled[1::2]))
    if max_pairs > 0:
        pairs = pairs[:max_pairs]
    rated = rate_pairs_from_target(
        pairs,
        target,
        temperature=temperature,
        tie_margin=tie_margin,
    )
    split = max(int(len(rated) * 0.8), 1)
    train_pairs, val_pairs = rated[:split], rated[split:]

    optimizer = Adam(reward_model.parameters(), lr=learning_rate)
    loss_fn = PairwiseLoss()
    regularization_loss = RegularizationLoss(regularization_type="L1", lambda_reg=weight_l1)
    output_regularization_loss = OutputRegularizationLoss(regularization_type="L1", lambda_reg=output_l1)
    best_state = deepcopy(reward_model.state_dict())
    best_val = float("inf")
    best_epoch = 0
    no_improvement = 0

    def _val_loss() -> float:
        if not val_pairs:
            return 0.0
        with th.no_grad():
            x1, x2, ratings = rated_pairs_to_tensors(val_pairs, convert_traj)
            return float(loss_fn(reward_model(x1), reward_model(x2), ratings).mean().item())

    for epoch in range(epochs):
        reward_model.train()
        random.shuffle(train_pairs)
        x1_all, x2_all, ratings_all = rated_pairs_to_tensors(train_pairs, convert_traj)
        running_loss, batches = 0.0, 0
        for start in range(0, len(train_pairs), batch_size):
            stop = min(start + batch_size, len(train_pairs))
            y1 = reward_model(x1_all[start:stop])
            y2 = reward_model(x2_all[start:stop])
            loss = loss_fn(y1, y2, ratings_all[start:stop])
            loss += (output_regularization_loss(y1) + output_regularization_loss(y2)) / 2
            data_loss = loss.sum() if loss_reduction == "sum" else loss.mean()
            total_loss = data_loss + regularization_loss(reward_model)
            optimizer.zero_grad()
            total_loss.backward()
            optimizer.step()
            running_loss += float(loss.mean().item())
            batches += 1

        reward_model.eval()
        val_loss = _val_loss()
        print(f"BT pretrain epoch {epoch}: train_loss={running_loss / max(batches, 1):.4f}, val_loss={val_loss:.4f}")
        if val_loss < best_val:
            best_val, best_epoch, no_improvement = val_loss, epoch, 0
            best_state = deepcopy(reward_model.state_dict())
        else:
            no_improvement += 1
            if no_improvement >= patience:
                print(f"stopping BT pretraining at epoch {epoch}; restoring epoch {best_epoch} val_loss={best_val:.4f}")
                reward_model.load_state_dict(best_state)
                break
    else:
        if val_pairs:
            reward_model.load_state_dict(best_state)

    return {
        "pretrain_pairs": len(rated),
        "pretrain_fragments": len(fragments),
        "pretrain_val_loss": best_val if val_pairs else None,
        "pretrain_bt_temperature": temperature,
        "pretrain_bt_tie_margin": tie_margin,
        "pretrain_bt_loss_reduction": loss_reduction,
        "pretrain_bt_weight_l1": weight_l1,
        "pretrain_bt_output_l1": output_l1,
        "pretrain_soft_label_fraction": float(sum(0.0 < pair.rating < 1.0 for pair in rated) / len(rated)),
        "pretrain_tie_label_fraction": float(sum(pair.rating == 0.5 for pair in rated) / len(rated)),
    }


def _preference_training_accuracy(
    reward_model: RewardModel,
    train_pairs: list[Preference],
    convert_traj: Callable[[Trajectory], list[list[float]]],
    use_delta_loss: bool,
    partial_mean: float,
    partial_std: float,
    partial_alpha: float,
) -> float:
    """Mean correctness on a complete preference buffer.

    Oracle-teacher ratings are hard 0/1 labels, where this is ordinary ranking
    accuracy. For a soft label, the contribution is the probability mass that
    the label assigns to the model's chosen side (and an exact 0.5 tie therefore
    contributes 0.5). This keeps the statistic meaningful for every supported
    ``Preference.rating`` without changing the hard-label B-Pref case.
    """
    if not train_pairs:
        return 0.0
    with th.no_grad():
        x1, x2, ratings = rated_pairs_to_tensors(train_pairs, convert_traj)
        score1, score2 = reward_model(x1), reward_model(x2)
        if use_delta_loss:
            partial1 = partial_reward_tensor(train_pairs, "t1", partial_mean, partial_std)
            partial2 = partial_reward_tensor(train_pairs, "t2", partial_mean, partial_std)
            if reward_model.gate_head is not None:
                score1 = score1 + reward_model.gate(x1) * partial1 * partial_alpha
                score2 = score2 + reward_model.gate(x2) * partial2 * partial_alpha
            else:
                alpha = reward_model.alpha if reward_model.alpha is not None else partial_alpha
                score1 = score1 + alpha * partial1
                score2 = score2 + alpha * partial2
        chose_first = score1.sum(dim=[1, 2]) > score2.sum(dim=[1, 2])
        correctness = th.where(chose_first, ratings, 1.0 - ratings)
        return float(correctness.mean().item())


def train_preference_reward_model(
    reward_model: RewardModel,
    train_pairs: list[Preference],
    val_pairs: list[Preference],
    convert_traj: Callable[[Trajectory], list[list[float]]],
    use_delta_loss: bool,
    batch_size: int,
    epochs: int,
    patience: int,
    learning_rate: float = 0.01,
    partial_mean: float = 0.0,
    partial_std: float = 1.0,
    partial_alpha: float = 1.0,
    partial_alpha_penalty: float = 0.0,
    partial_prediction_coef: float = 0.0,
    gate_holdout: bool = False,
    gate_learning_rate: float | None = None,
    gate_epochs: int | None = None,
    gate_patience: int = 10,
    gate_prior_penalty: float = 0.0,
    loss_reduction: str = "sum",
    weight_l1: float = 0.01,
    output_l1: float = 0.001,
    fixed_epochs_without_validation: bool = False,
    train_accuracy_stop: float | None = None,
) -> dict | None:
    if not train_pairs:
        return None
    if loss_reduction not in ("sum", "mean"):
        raise ValueError("loss_reduction must be 'sum' or 'mean'")
    if weight_l1 < 0 or output_l1 < 0:
        raise ValueError("reward-model L1 penalties must be non-negative")
    if train_accuracy_stop is not None and not 0.0 <= train_accuracy_stop <= 1.0:
        raise ValueError("train_accuracy_stop must be between 0 and 1")

    optimizer = Adam(reward_model.parameters(), lr=learning_rate)
    preference_loss = DeltaLoss() if use_delta_loss else PairwiseLoss()
    gate_loss = PairwiseLoss()  # Bradley-Terry on the gated composed reward h + g*partial
    regularization_loss = RegularizationLoss(regularization_type="L1", lambda_reg=weight_l1)
    output_regularization_loss = OutputRegularizationLoss(regularization_type="L1", lambda_reg=output_l1)
    best_state = deepcopy(reward_model.state_dict())
    best_val = float("inf")
    best_epoch = 0
    no_improvement = 0
    epochs_completed = 0
    last_epoch_train_loss = None
    train_accuracy_at_stop = None
    stopped_by_train_accuracy = False
    stop_reason = "max_epochs"

    for epoch in range(epochs):
        # train()/eval() only affect the optional output batch-norm; they are
        # no-ops for the default model, which has no train/eval-sensitive layers.
        reward_model.train()
        random.shuffle(train_pairs)
        t1_tensor, t2_tensor, ratings = rated_pairs_to_tensors(train_pairs, convert_traj)
        running_loss = 0.0
        batches = 0

        for batch_start in range(0, len(train_pairs), batch_size):
            batch_end = min(batch_start + batch_size, len(train_pairs))
            batch_pairs = train_pairs[batch_start:batch_end]
            x1 = t1_tensor[batch_start:batch_end]
            x2 = t2_tensor[batch_start:batch_end]
            y1 = reward_model(x1)
            y2 = reward_model(x2)
            rating_batch = ratings[batch_start:batch_end]

            if use_delta_loss and reward_model.gate_head is not None:
                # per-state gate: R_hat = h(s,a) + g(s,a) * alpha * partial(s,a), g in [0,1]
                g1 = reward_model.gate(x1)
                g2 = reward_model.gate(x2)
                t1_partial = partial_reward_tensor(batch_pairs, "t1", partial_mean, partial_std) * partial_alpha
                t2_partial = partial_reward_tensor(batch_pairs, "t2", partial_mean, partial_std) * partial_alpha
                loss = gate_loss(y1 + g1 * t1_partial, y2 + g2 * t2_partial, rating_batch)
                if gate_prior_penalty > 0:
                    loss = loss + gate_prior_penalty * (
                        ((1.0 - g1) ** 2).mean(dim=[1, 2]) + ((1.0 - g2) ** 2).mean(dim=[1, 2])
                    )
            elif use_delta_loss:
                alpha = reward_model.alpha if reward_model.alpha is not None else partial_alpha
                t1_partial = partial_reward_tensor(batch_pairs, "t1", partial_mean, partial_std)
                t2_partial = partial_reward_tensor(batch_pairs, "t2", partial_mean, partial_std)
                loss = preference_loss(y1, y2, t1_partial, t2_partial, rating_batch, alpha)
            else:
                loss = preference_loss(y1, y2, rating_batch)

            loss += (output_regularization_loss.forward(y1) + output_regularization_loss.forward(y2)) / 2
            data_loss = loss.sum() if loss_reduction == "sum" else loss.mean()
            total_loss = data_loss + regularization_loss.forward(reward_model)
            if use_delta_loss and reward_model.alpha is not None:
                total_loss = total_loss + partial_alpha_penalty * (reward_model.alpha - partial_alpha) ** 2
            if use_delta_loss and partial_prediction_coef > 0 and reward_model.partial_head is not None:
                prediction_loss = (
                    th.nn.functional.mse_loss(reward_model.predict_partial(x1), t1_partial)
                    + th.nn.functional.mse_loss(reward_model.predict_partial(x2), t2_partial)
                ) / 2
                total_loss = total_loss + partial_prediction_coef * prediction_loss

            optimizer.zero_grad()
            total_loss.backward()
            optimizer.step()
            running_loss += float(loss.mean().item())
            batches += 1

        reward_model.eval()
        epochs_completed = epoch + 1
        train_loss = running_loss / max(batches, 1)
        last_epoch_train_loss = train_loss
        train_accuracy = None
        if train_accuracy_stop is not None:
            train_accuracy = _preference_training_accuracy(
                reward_model,
                train_pairs,
                convert_traj,
                use_delta_loss,
                partial_mean,
                partial_std,
                partial_alpha,
            )
        accuracy_suffix = f", train_accuracy={train_accuracy:.4f}" if train_accuracy is not None else ""
        if val_pairs or not fixed_epochs_without_validation:
            val_loss = validate_preference_reward_model(
                reward_model, val_pairs, convert_traj, preference_loss, use_delta_loss, partial_mean, partial_std, partial_alpha
            )
            print(f"reward model epoch {epoch}: train_loss={train_loss:.4f}, val_loss={val_loss:.4f}{accuracy_suffix}")
            if val_loss < best_val:
                best_val = val_loss
                best_epoch = epoch
                best_state = deepcopy(reward_model.state_dict())
                no_improvement = 0
            else:
                no_improvement += 1
        else:
            # PEBBLE/B-Pref train each ensemble member on the full preference
            # buffer. With no held-out fold there is no honest early-stopping
            # signal, so run the requested fixed number of epochs.
            print(f"reward model epoch {epoch}: train_loss={train_loss:.4f} (full-data training){accuracy_suffix}")

        # B-Pref checks strict accuracy > 0.97 after a complete buffer pass.
        # This opt-in implementation applies that rule independently to each
        # member because this codebase trains ensemble members serially. It does
        # not claim B-Pref's synchronized ensemble loop or persistent optimizer.
        if train_accuracy is not None and train_accuracy > train_accuracy_stop:
            stopped_by_train_accuracy = True
            stop_reason = "train_accuracy"
            train_accuracy_at_stop = train_accuracy
            print(
                f"stopping reward model at epoch {epoch}: train_accuracy={train_accuracy:.4f} "
                f"> {train_accuracy_stop:.4f}"
            )
            break
        if (val_pairs or not fixed_epochs_without_validation) and no_improvement >= patience:
            stop_reason = "validation_patience"
            print(f"stopping reward model at epoch {epoch}; restoring epoch {best_epoch} val_loss={best_val:.4f}")
            reward_model.load_state_dict(best_state)
            break

    # naive + gate: phase 2 — freeze the trained reward, learn only the per-state gate
    if not use_delta_loss and reward_model.gate_head is not None:
        train_gate_head(
            reward_model,
            train_pairs,
            val_pairs,
            convert_traj,
            gate_epochs if gate_epochs is not None else epochs,
            batch_size,
            gate_learning_rate if gate_learning_rate is not None else learning_rate,
            partial_mean,
            partial_std,
            partial_alpha=partial_alpha,
            holdout=gate_holdout,
            patience=gate_patience,
            prior_penalty=gate_prior_penalty,
        )

    reward_model.eval()
    final_train_accuracy = _preference_training_accuracy(
        reward_model,
        train_pairs,
        convert_traj,
        use_delta_loss,
        partial_mean,
        partial_std,
        partial_alpha,
    )
    return {
        "epochs_completed": epochs_completed,
        "last_epoch_train_loss": last_epoch_train_loss,
        "final_train_accuracy": final_train_accuracy,
        "train_accuracy_at_stop": train_accuracy_at_stop,
        "stopped_by_train_accuracy": stopped_by_train_accuracy,
        "stop_reason": stop_reason,
        "n_train_pairs": len(train_pairs),
        "n_val_pairs": len(val_pairs),
        "train_accuracy_stop": train_accuracy_stop,
        "best_epoch_zero_based": best_epoch if best_val < float("inf") else None,
        "best_val_loss": best_val if best_val < float("inf") else None,
    }


def train_gate_head(
    reward_model,
    train_pairs,
    val_pairs,
    convert_traj,
    epochs,
    batch_size,
    learning_rate,
    partial_mean,
    partial_std,
    partial_alpha: float = 1.0,
    holdout: bool = False,
    patience: int = 10,
    prior_penalty: float = 0.0,
):
    """Phase 2 of the naive frozen-trunk gate: freeze the whole reward model and
    train ONLY the gate head, minimizing the preference loss on the composed
    reward r_pred + g(s,a)*alpha*partial. The trunk is frozen, so the gate reads
    the already-learned features and cannot disturb r_pred.

    With holdout=True the gate is fit and early-stopped on two halves of the
    pairs the reward model was NOT gradient-trained on. This matters: on its own
    training pairs r_pred has partly memorized the labels, so the residual the
    gate could explain is near zero there and the gate collapses to g ~ 0
    regardless of whether the partial is actually useful. Scoring the gate on
    those same pairs would bake the same bias into the stopping rule, so both
    halves come from the held-out side.

    prior_penalty pulls g toward 1 (= use the partial fully, the naive baseline),
    so shrinking the partial has to be paid for with preference evidence.
    """
    if holdout and len(val_pairs) >= 4:
        shuffled = list(val_pairs)
        random.shuffle(shuffled)
        cut = len(shuffled) // 2
        fit_pairs, score_pairs = shuffled[:cut], shuffled[cut:]
    else:
        fit_pairs, score_pairs = list(train_pairs), []
    if not fit_pairs:
        return

    for parameter in reward_model.parameters():
        parameter.requires_grad_(False)
    for parameter in reward_model.gate_head.parameters():
        parameter.requires_grad_(True)
    optimizer = Adam(reward_model.gate_head.parameters(), lr=learning_rate)
    loss_fn = PairwiseLoss()
    reward_model.eval()  # freeze any batch-norm running stats

    best_state = deepcopy(reward_model.gate_head.state_dict())
    best_val = float("inf")
    best_epoch = 0
    no_improvement = 0

    for epoch in range(epochs):
        random.shuffle(fit_pairs)
        t1_tensor, t2_tensor, ratings = rated_pairs_to_tensors(fit_pairs, convert_traj)
        running_loss, batches = 0.0, 0
        for batch_start in range(0, len(fit_pairs), batch_size):
            batch_end = min(batch_start + batch_size, len(fit_pairs))
            batch_pairs = fit_pairs[batch_start:batch_end]
            x1, x2 = t1_tensor[batch_start:batch_end], t2_tensor[batch_start:batch_end]
            with th.no_grad():
                h1, h2 = reward_model(x1), reward_model(x2)  # frozen r_pred
            g1, g2 = reward_model.gate(x1), reward_model.gate(x2)  # grads only into gate_head
            t1_partial = partial_reward_tensor(batch_pairs, "t1", partial_mean, partial_std) * partial_alpha
            t2_partial = partial_reward_tensor(batch_pairs, "t2", partial_mean, partial_std) * partial_alpha
            loss = loss_fn(h1 + g1 * t1_partial, h2 + g2 * t2_partial, ratings[batch_start:batch_end])
            total_loss = loss.sum()
            if prior_penalty > 0:
                total_loss = total_loss + prior_penalty * (((1.0 - g1) ** 2).mean() + ((1.0 - g2) ** 2).mean())
            optimizer.zero_grad()
            total_loss.backward()
            optimizer.step()
            running_loss += float(loss.mean().item())
            batches += 1

        train_loss = running_loss / max(batches, 1)
        if not score_pairs:
            print(f"gate epoch {epoch}: loss2={train_loss:.4f}")
            continue

        val_loss = _gate_validation_loss(
            reward_model, score_pairs, convert_traj, loss_fn, partial_mean, partial_std, partial_alpha
        )
        print(f"gate epoch {epoch}: loss2={train_loss:.4f}, val_loss={val_loss:.4f}")
        if val_loss < best_val:
            best_val, best_epoch, no_improvement = val_loss, epoch, 0
            best_state = deepcopy(reward_model.gate_head.state_dict())
        else:
            no_improvement += 1
            if no_improvement >= patience:
                print(f"stopping gate at epoch {epoch}; restoring epoch {best_epoch} val_loss={best_val:.4f}")
                reward_model.gate_head.load_state_dict(best_state)
                break
    else:
        if score_pairs:
            reward_model.gate_head.load_state_dict(best_state)

    for parameter in reward_model.parameters():
        parameter.requires_grad_(True)


def _gate_validation_loss(reward_model, pairs, convert_traj, loss_fn, partial_mean, partial_std, partial_alpha):
    with th.no_grad():
        t1_tensor, t2_tensor, ratings = rated_pairs_to_tensors(pairs, convert_traj)
        h1, h2 = reward_model(t1_tensor), reward_model(t2_tensor)
        g1, g2 = reward_model.gate(t1_tensor), reward_model.gate(t2_tensor)
        t1_partial = partial_reward_tensor(pairs, "t1", partial_mean, partial_std) * partial_alpha
        t2_partial = partial_reward_tensor(pairs, "t2", partial_mean, partial_std) * partial_alpha
        return float(loss_fn(h1 + g1 * t1_partial, h2 + g2 * t2_partial, ratings).mean().item())


def split_preference_k_folds(rated_pairs: list[Preference], k: int) -> list[list[Preference]]:
    if k <= 0:
        raise ValueError("k must be greater than zero")
    folds = [[] for _ in range(k)]
    shuffled = list(rated_pairs)
    random.shuffle(shuffled)
    for index, pair in enumerate(shuffled):
        folds[index % k].append(pair)
    return folds


def train_preference_reward_ensemble(
    reward_models: list[RewardModel],
    rated_pairs: list[Preference],
    convert_traj: Callable[[Trajectory], list[list[float]]],
    use_delta_loss: bool,
    batch_size: int,
    epochs: int,
    patience: int,
    learning_rate: float = 0.01,
    partial_mean: float = 0.0,
    partial_std: float = 1.0,
    partial_alpha: float = 1.0,
    partial_alpha_penalty: float = 0.0,
    partial_prediction_coef: float = 0.0,
    gate_holdout: bool = False,
    gate_learning_rate: float | None = None,
    gate_epochs: int | None = None,
    gate_patience: int = 10,
    gate_prior_penalty: float = 0.0,
    loss_reduction: str = "sum",
    weight_l1: float = 0.01,
    output_l1: float = 0.001,
    training_mode: str = "kfold",
    train_accuracy_stop: float | None = None,
    bootstrap: bool = False,
) -> list[dict]:
    if not rated_pairs:
        return []
    if not reward_models:
        raise ValueError("reward_models must not be empty")
    if training_mode not in ("kfold", "full"):
        raise ValueError("training_mode must be 'kfold' or 'full'")
    if bootstrap and training_mode != "full":
        raise ValueError("bootstrap resampling applies to training_mode='full'")

    folds = split_preference_k_folds(rated_pairs, len(reward_models)) if training_mode == "kfold" else None
    member_stats = []
    for fold_index, reward_model in enumerate(reward_models):
        if training_mode == "full":
            # B-Pref gives every member the identical buffer in a different order.
            # Once a member fits that buffer perfectly the ensemble collapses to one
            # function, and disagreement-based query selection has nothing to measure
            # (observed here: max-min member training accuracy is exactly 0.000 on
            # Pusher and Walker2d). A bootstrap resample keeps the members distinct
            # at the cost of ~37% of the pairs being unseen by any given member.
            if bootstrap:
                train_pairs = [rated_pairs[random.randrange(len(rated_pairs))] for _ in range(len(rated_pairs))]
                val_pairs = []
            else:
                train_pairs, val_pairs = list(rated_pairs), []
        else:
            assert folds is not None
            val_pairs = folds[fold_index]
            train_pairs = [
                pair
                for other_fold_index, fold in enumerate(folds)
                if other_fold_index != fold_index
                for pair in fold
            ]
            if not train_pairs:
                train_pairs = list(rated_pairs)
        print(
            f"training reward ensemble member {fold_index + 1}/{len(reward_models)} "
            f"on {len(train_pairs)} pairs; validating on {len(val_pairs)} pairs"
        )
        stats = train_preference_reward_model(
            reward_model,
            train_pairs,
            val_pairs,
            convert_traj=convert_traj,
            use_delta_loss=use_delta_loss,
            batch_size=batch_size,
            epochs=epochs,
            patience=patience,
            learning_rate=learning_rate,
            loss_reduction=loss_reduction,
            weight_l1=weight_l1,
            output_l1=output_l1,
            partial_mean=partial_mean,
            partial_std=partial_std,
            partial_alpha=partial_alpha,
            partial_alpha_penalty=partial_alpha_penalty,
            partial_prediction_coef=partial_prediction_coef,
            gate_holdout=gate_holdout,
            gate_learning_rate=gate_learning_rate,
            gate_epochs=gate_epochs,
            gate_patience=gate_patience,
            gate_prior_penalty=gate_prior_penalty,
            fixed_epochs_without_validation=training_mode == "full",
            train_accuracy_stop=train_accuracy_stop,
        )
        if stats is not None:
            member_stats.append(
                {
                    "member_index": fold_index,
                    "training_mode": training_mode,
                    "bootstrap": bootstrap,
                    "n_unique_train_pairs": len({id(pair) for pair in train_pairs}),
                    **stats,
                }
            )
    return member_stats


def validate_preference_reward_model(
    reward_model,
    val_pairs,
    convert_traj,
    preference_loss,
    use_delta_loss: bool,
    partial_mean: float = 0.0,
    partial_std: float = 1.0,
    partial_alpha: float = 1.0,
) -> float:
    if not val_pairs:
        return 0.0
    with th.no_grad():
        t1_tensor, t2_tensor, ratings = rated_pairs_to_tensors(val_pairs, convert_traj)
        y1 = reward_model(t1_tensor)
        y2 = reward_model(t2_tensor)
        if use_delta_loss and reward_model.gate_head is not None:
            g1 = reward_model.gate(t1_tensor)
            g2 = reward_model.gate(t2_tensor)
            t1_partial = partial_reward_tensor(val_pairs, "t1", partial_mean, partial_std)
            t2_partial = partial_reward_tensor(val_pairs, "t2", partial_mean, partial_std)
            return float(PairwiseLoss()(y1 + g1 * t1_partial, y2 + g2 * t2_partial, ratings).mean().item())
        if use_delta_loss:
            alpha = reward_model.alpha if reward_model.alpha is not None else partial_alpha
            t1_partial = partial_reward_tensor(val_pairs, "t1", partial_mean, partial_std)
            t2_partial = partial_reward_tensor(val_pairs, "t2", partial_mean, partial_std)
            return float(preference_loss(y1, y2, t1_partial, t2_partial, ratings, alpha).mean().item())
        return float(preference_loss(y1, y2, ratings).mean().item())
